### DISCUSSION TITLE
The workflow needs to be triggered 3 Times to get the Deployment Preview

### DISCUSSION THREAD

**Discussion by anishdalvi** [matthew-petrie/shopify-theme-actions#220] [General]
I am working with Shopify Theme in which the workflow is perfectly setup with installation of Shopify App in the store and creating all the required variables in the Github Account.

1. Now the issue is that whenever I put a PR, I can see this error

![image](https://github.com/user-attachments/assets/9195f062-27ab-4877-8a52-253d3de93911)

2. In the 2nd PR, i mean when I push the new commits just by editing a letter in some text.file (Just to have a new commit) and not changing anything the templates folder, I can see some errors disappears

![image](https://github.com/user-attachments/assets/c15b4099-077f-4dd9-ba7b-e609366f4772)

3. And when 3rd new commits comes, all the errors are gone and I can see the comment from bot of the Deployment Preview!

![image](https://github.com/user-attachments/assets/bc5b8339-4caf-4fe1-861b-23252af57505)

4. The Comment:

![image](https://github.com/user-attachments/assets/172c08d5-aee4-450e-a9fc-0ecfd146945a)

5. Also, works well when the theme is removed after closing the PR

![image](https://github.com/user-attachments/assets/ac679d1c-635b-4013-b5d8-7bfea70dfa5a)

**I also tried Running the workflow manually, and it is clearly proved that Triggering the workflow 3 times, solved the issue**

Also, I have no idea how the errors are automatically resolved just by committing new commits. Let me know where am I going wrong.

Thanks!

Here is the code for theme-preview.yml

```
name: Shopify Theme Management

on:
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  manage-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug API Authentication
        if: github.event_name == 'pull_request'
        run: |
          curl -v -X GET "https://${{ secrets.SHOP_STORE }}/admin/api/2023-10/shop.json" \
            -H "Content-Type: application/json" \
            -H "X-Shopify-Access-Token: ${{ secrets.SHOP_PASSWORD }}"
        env:
          SHOP_STORE: ${{ secrets.SHOP_STORE }}
          SHOP_PASSWORD: ${{ secrets.SHOP_PASSWORD }}

      # Create and deploy a PR specific Shopify theme when PR is opened/updated
      - name: Deploy PR-specific Shopify theme
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: matthew-petrie/shopify-theme-actions@1.2.2
        with:
          ACTION: 'DEPLOYMENT_PREVIEW'
          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
          SHOPIFY_THEME_DIRECTORY: '.'
          SHOPIFY_ALLOW_LIVE_THEME_DEPLOYMENT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log deployment detail
        run: |
          echo "Deployment attempt completed"
          echo "Files processed: ${{ steps.deploy-theme.outputs.FILES_PROCESSED }}"
          echo "Files updated: ${{ steps.deploy-theme.outputs.FILES_UPDATED }}"
          echo "Errors encountered: ${{ steps.deploy-theme.outputs.ERRORS }}"

      # Remove the previously created PR specific Shopify theme when PR is closed
      - name: Remove PR-specific Shopify theme
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: matthew-petrie/shopify-theme-actions@1.2.2
        with:
          ACTION: 'REMOVE_DEPLOYMENT_PREVIEW_THEME'
          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOPIFY_THEME_DIRECTORY: '.'
          SHOPIFY_ALLOW_LIVE_THEME_DEPLOYMENT: false

       # Add a comment when the deployment preview is removed
      - name: Comment on PR closure
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🗑️ The Shopify theme deployment preview has been removed.'
            })

      # Add a step that always runs for testing
      - name: Echo test
        run: |
          echo "Workflow is running. Event name: ${{ github.event_name }}"

```
